# This is a basic workflow to help you get started with Actions
name: Docker Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

env:
  AZURE_CONTAINER_REGISTRY: "<your-acr-name>.azurecr.io"
  DOCKER_IMAGE_NAME: "<your-docker-image-name>"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_SP_ID }}
        password: ${{ secrets.AZURE_SP_PASSWORD }}

    - name: Build Docker image with build arguments
      run: |
        docker build \
          --build-arg ARG1=${{ secrets.BUILD_ARG1 }} \
          --build-arg ARG2=${{ secrets.BUILD_ARG2 }} \
          -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} \
          .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
