name: Docker Build and Push to Azure Container Registry for backend

on:
  push:
    branches:
      - feature/env-variable

env:
  AZURE_CONTAINER_REGISTRY: "testing2sfa.azurecr.io"
  DOCKER_IMAGE_NAME: "backend"
  DOCKER_IMAGE_Version: "v1"
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Debug Docker CLI
      run: |
          docker version
          docker info
          echo "DOCKER_CLI_EXPERIMENTAL=$DOCKER_CLI_EXPERIMENTAL"

    - name: Disable BuildX (if needed)
      run: export DOCKER_CLI_EXPERIMENTAL=disabled

    - name: Build Docker image with build arguments
      run: |
          cd backend
          docker build \
              --build-arg APPLICATION_INSIGHTS_CONNECTION_STRING="${{ secrets.APPLICATION_INSIGHTS_CONNECTION_STRING }}" \
              --build-arg AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              -t ${{ env.AZURE_CONTAINER_REGISTRY }}/backend:${{ env.DOCKER_IMAGE_Version }} .
    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_Version }}