name: Docker Build and Push to Azure Container Registry

on:
  push:
    branches:
      - feature/env-variable

env:
  AZURE_CONTAINER_REGISTRY: "testing2sfa.azurecr.io"
  DOCKER_IMAGE_NAME: "backend"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Debug Docker CLI
      run: |
          docker version
          docker info
          echo "DOCKER_CLI_EXPERIMENTAL=$DOCKER_CLI_EXPERIMENTAL"

    - name: Disable BuildX (if needed)
      run: export DOCKER_CLI_EXPERIMENTAL=disabled

    - name: Build Docker image with build arguments
      run: |
          cd backend
          docker build \
            --build-arg APPLICATION_INSIGHTS_CONNECTION_STRING="InstrumentationKey=62cff588-b058-4a53-b029-8ec912b0d606;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/;ApplicationId=352bcf8a-3087-453c-a76a-1d708cf329cd" \
            --build-arg AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=formsubmissiondata;AccountKey=hII7sqwGGwrinBr0Rs5jf74GN6nho3wgJH3kUgYYyQE1lk9DEWHBtq3XPJ5kJ2FpNcxn1G3XRsaV+AStNNWvFw==;EndpointSuffix=core.windows.net \
            -t testing2sfa.azurecr.io/backend:latest .
    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}